import { render, screen } from '@testing-library/react';
import RootLayout, { metadata } from '../layout';

// Mock Next.js font imports
const mockGeist = jest.fn(() => ({
  variable: '--font-geist-sans',
}));

const mockGeistMono = jest.fn(() => ({
  variable: '--font-geist-mono',
}));

jest.mock('next/font/google', () => ({
  Geist: mockGeist,
  Geist_Mono: mockGeistMono,
}));

// Mock CSS import
jest.mock('../globals.css', () => ({}));

describe('RootLayout', () => {
  const mockChildren = <div data-testid="mock-children">Test Content</div>;

  beforeEach(() => {
    // Clear all mocks before each test
    jest.clearAllMocks();
  });

  test('renders without crashing', () => {
    render(<RootLayout>{mockChildren}</RootLayout>);
  });

  test('renders children correctly', () => {
    render(<RootLayout>{mockChildren}</RootLayout>);
    expect(screen.getByTestId('mock-children')).toBeInTheDocument();
    expect(screen.getByText('Test Content')).toBeInTheDocument();
  });

  test('applies correct HTML lang attribute', () => {
    const { container } = render(<RootLayout>{mockChildren}</RootLayout>);
    const htmlElement = container.querySelector('html');
    expect(htmlElement).toHaveAttribute('lang', 'en');
  });

  test('applies font variables to body element', () => {
    const { container } = render(<RootLayout>{mockChildren}</RootLayout>);
    const bodyElement = container.querySelector('body');
    
    expect(bodyElement).toHaveClass('--font-geist-sans');
    expect(bodyElement).toHaveClass('--font-geist-mono');
    expect(bodyElement).toHaveClass('antialiased');
  });

  test('has correct document structure', () => {
    const { container } = render(<RootLayout>{mockChildren}</RootLayout>);
    
    // Check HTML structure
    expect(container.querySelector('html')).toBeInTheDocument();
    expect(container.querySelector('body')).toBeInTheDocument();
    
    // Ensure children are inside body
    const bodyElement = container.querySelector('body');
    expect(bodyElement).toContainElement(screen.getByTestId('mock-children'));
  });

  test('renders multiple children correctly', () => {
    const multipleChildren = (
      <>
        <div data-testid="child-1">Child 1</div>
        <div data-testid="child-2">Child 2</div>
      </>
    );

    render(<RootLayout>{multipleChildren}</RootLayout>);
    
    expect(screen.getByTestId('child-1')).toBeInTheDocument();
    expect(screen.getByTestId('child-2')).toBeInTheDocument();
  });

  test('handles empty children', () => {
    render(<RootLayout>{null}</RootLayout>);
    const bodyElement = document.querySelector('body');
    expect(bodyElement).toBeInTheDocument();
  });

  test('body has correct className structure', () => {
    const { container } = render(<RootLayout>{mockChildren}</RootLayout>);
    const bodyElement = container.querySelector('body');
    
    // Check that className includes all expected parts
    const className = bodyElement.className;
    expect(className).toMatch(/--font-geist-sans/);
    expect(className).toMatch(/--font-geist-mono/);
    expect(className).toMatch(/antialiased/);
  });
});

describe('metadata export', () => {
  test('exports correct metadata object', () => {
    expect(metadata).toBeDefined();
    expect(metadata).toEqual({
      title: "Create Next App",
      description: "Generated by create next app",
    });
  });

  test('metadata has correct title', () => {
    expect(metadata.title).toBe("Create Next App");
  });

  test('metadata has correct description', () => {
    expect(metadata.description).toBe("Generated by create next app");
  });

  test('metadata object structure', () => {
    expect(typeof metadata).toBe('object');
    expect(Object.keys(metadata)).toEqual(['title', 'description']);
  });
});

describe('Font imports', () => {
  test('Geist font is imported and configured correctly', () => {
    expect(mockGeist).toHaveBeenCalledWith({
      variable: "--font-geist-sans",
      subsets: ["latin"],
    });
  });

  test('Geist_Mono font is imported and configured correctly', () => {
    expect(mockGeistMono).toHaveBeenCalledWith({
      variable: "--font-geist-mono",
      subsets: ["latin"],
    });
  });
});